'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path'),crypto=require('crypto');
const {profile,verifyProfile,classifyWarnings,corpus}=require('../tools/automation.cjs');
const {strictLoad}=require('../tools/strict-sim.cjs');
function temp(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'wc3-controls-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return dir;}
test('empty editor corpus cannot pass',t=>{const root=temp(t);const r=corpus(path.resolve(__dirname,'../automation/editor-corpus.json'),path.join(root,'report'));assert.equal(r.status,'NO_FIXTURES');assert.equal(r.editorReopen,'NOT_RUN');});
test('warnings need exact content, source, reason and a future expiry',()=>{const check={id:'camera',status:'WARN',detail:'Exact diagnostic'};const fingerprint=crypto.createHash('sha256').update(JSON.stringify({id:check.id,detail:check.detail})).digest('hex');const waiver={id:'camera',fingerprint,sourceSha256:'input',reason:'Reviewed camera-only local state',expires:'2026-09-30T00:00:00Z'};const now=Date.parse('2026-09-15T00:00:00Z');assert.equal(classifyWarnings([check],'input',[waiver],now).blocked.length,0);assert.equal(classifyWarnings([check],'other',[waiver],now).blocked.length,1);assert.equal(classifyWarnings([check],'input',[{...waiver,expires:'2026-09-01'}],now).blocked.length,1);assert.equal(classifyWarnings([],'input',[waiver],now).unused.length,1);});
test('profiles hash supplied bytes and never invent a verified build label',t=>{const root=temp(t),common=path.join(root,'common.j'),bj=path.join(root,'Blizzard.j'),exe=path.join(root,'sample.bin');fs.writeFileSync(common,'native Fixture takes nothing returns nothing\n');fs.writeFileSync(bj,'// parser fixture');fs.writeFileSync(exe,'file-hashing fixture; not an executable');const pin=profile(common,bj,exe,path.join(root,'pin.json'),'unverified');assert.equal(pin.labelVerified,false);assert.equal(pin.runtimeValidated,false);verifyProfile(pin,common,bj,exe);fs.appendFileSync(common,'changed');assert.throws(()=>verifyProfile(pin,common,bj,exe),/differs/);});
test('strict adapter rejects unknown effect behavior rather than reporting success',()=>{const sim=strictLoad(null,{script:'',config:false,main:false});assert.throws(()=>sim.call('AddSpecialEffect','x',0,0),/Unmodelled WC3 native/);});
test('strict adapter allows exact explicit exceptions only',()=>{const sim=strictLoad(null,{script:'',config:false,main:false,allowStubs:['AddSpecialEffect']});sim.call('AddSpecialEffect','x',0,0);assert.throws(()=>sim.call('PolledWait',1),/Unmodelled WC3 native/);});
