#!/usr/bin/env bash
# OPTIONAL third-opinion cross-validation with War3Net (C#/.NET, MIT) —
# v6.x packages (War3Net.Build.Core 6.* ships a net6.0 target, consumable
# from the net8.0 SDK this script asks for).
# See docs/PIPELINE.md §6. This is documentation-as-a-script: dotnet is NOT a
# dependency of this toolkit and nothing else here needs it. The script
# refuses to install anything on its own; it tells you what to install and,
# when dotnet is already present, scaffolds and runs the checker.
#
# Usage:
#   bash scripts/crossvalidate-war3net.sh [--dump-triggers] <extracted-map-dir>
# where <extracted-map-dir> is the output of tools/w3x-extract.js
# (raw war3map.* files).
#
# Default mode parses war3map.w3i and war3map.w3e with War3Net.Build.Core and
# reports pass/fail per file. War3Net handles both classic AND Reforged
# format versions, so it is the tie-breaker when wc3maptranslator and
# mdx-m3-viewer-th disagree (e.g. the 1.32 w3c camera layout — docs/FORMATS.md).
#
# --dump-triggers additionally reads war3map.wtg (WE trigger definitions) and
# war3map.wct (custom-text triggers) — the one format class the rest of this
# toolkit marks opaque — and writes READ-ONLY JSON dumps under
# <extracted-map-dir>/_triggers/ (war3map.wtg.json, war3map.wct.json).
# Underscore path = diagnostics only, never repacked (same convention as
# _viewer/ and _unknown/). wtg parsing resolves trigger functions against
# War3Net's built-in community TriggerData (TriggerData.Default); no game
# files are needed or shipped. Honest scope: protectors delete wtg/wct and
# the game never reads them — this is unprotected-map ANALYSIS, not a build
# path (wtg AUTHORING stays deferred, docs/reference/ambitious-maps-analysis.md §6).
#
# --make-sample-triggers <out-dir> (test helper): writes a minimal synthetic
# war3map.wtg + war3map.wct generated by War3Net itself (our own artifact —
# bundled maps ship no wtg because WE-only files are not part of map sources
# here). Used by test/war3net.test.js.
#
# The compiled checker is cached under
# ${WC3_WAR3NET_CACHE:-$HOME/.cache/wc3-war3net} — first run downloads NuGet
# packages, later runs rebuild incrementally (a few seconds).
set -euo pipefail

MODE="check"
if [ "${1:-}" = "--dump-triggers" ]; then MODE="dump"; shift; fi
if [ "${1:-}" = "--make-sample-triggers" ]; then MODE="make-sample"; shift; fi

TARGET="${1:-}"
if [ -z "$TARGET" ]; then
    echo "usage: bash scripts/crossvalidate-war3net.sh [--dump-triggers] <extracted-map-dir>" >&2
    echo "       bash scripts/crossvalidate-war3net.sh --make-sample-triggers <out-dir>" >&2
    echo "  (produce the dir with: node tools/w3x-extract.js <map.w3x> <dir>)" >&2
    exit 2
fi
if [ "$MODE" != "make-sample" ] && [ ! -d "$TARGET" ]; then
    echo "not a directory: $TARGET" >&2
    exit 2
fi

if ! command -v dotnet >/dev/null 2>&1; then
    cat >&2 <<'EOF'
dotnet not found. War3Net cross-validation is OPTIONAL — install the SDK only
if you actually need a third opinion (or the wtg/wct trigger dump):

    sudo apt-get install -y dotnet-sdk-8.0

then re-run this script. Nothing else in this toolkit needs dotnet.
EOF
    exit 3
fi

WORK="${WC3_WAR3NET_CACHE:-${XDG_CACHE_HOME:-$HOME/.cache}/wc3-war3net}/check6"
mkdir -p "$WORK"

# Minimal checker project (the "check program pattern" from docs/PIPELINE.md):
# one console app + a War3Net.Build.Core 6.* reference. Parse success IS the
# check — v6 reads via BinaryReader extension methods (ReadMapInfo /
# ReadMapEnvironment / ReadMapTriggers / ReadMapCustomTextTriggers; the v5
# static MapInfo.Parse API is gone).
cat > "$WORK/check.csproj" <<'EOF'
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>wc3-war3net-check</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="War3Net.Build.Core" Version="6.*" />
  </ItemGroup>
</Project>
EOF
cat > "$WORK/Program.cs" <<'EOF'
// War3Net v6 third-opinion checker + wtg/wct dumper.
// Modes: check <dir> | dump <dir> | make-sample <dir>   (see the shell wrapper)
using System.Collections;
using System.Reflection;
using System.Text.Json;
using War3Net.Build.Extensions;
using War3Net.Build.Script;

var mode = args.Length > 0 ? args[0] : "";
var dir = args.Length > 1 ? args[1] : "";
var failures = 0;

void Check(string name, Action<string> parse)
{
    var path = Path.Combine(dir, name);
    if (!File.Exists(path)) { Console.WriteLine($"SKIP  {name} (absent)"); return; }
    try { parse(path); Console.WriteLine($"PASS  {name} (War3Net parse OK)"); }
    catch (Exception e) { Console.WriteLine($"FAIL  {name} ({e.Message})"); failures++; }
}

// JSON-safe plain projection (typed graph -> dictionaries/lists; enums by
// name; the concrete TriggerItem subclass recorded as _type). READ-ONLY
// diagnostics — this schema is a dump, not a build-source dialect.
static object? ToPlain(object? v, int depth)
{
    if (v is null) return null;
    if (depth > 24) return "[max depth]";
    var t = v.GetType();
    if (v is string || v is bool || t.IsPrimitive || v is decimal) return v;
    if (t.IsEnum) return v.ToString();
    if (v is IDictionary d)
    {
        var o = new Dictionary<string, object?>();
        foreach (DictionaryEntry e in d) o[e.Key?.ToString() ?? "null"] = ToPlain(e.Value, depth + 1);
        return o;
    }
    if (v is IEnumerable en)
    {
        var l = new List<object?>();
        foreach (var x in en) l.Add(ToPlain(x, depth + 1));
        return l;
    }
    var obj = new Dictionary<string, object?> { ["_type"] = t.Name };
    foreach (var p in t.GetProperties(BindingFlags.Public | BindingFlags.Instance))
    {
        if (!p.CanRead || p.GetIndexParameters().Length != 0) continue;
        try { obj[p.Name] = ToPlain(p.GetValue(v), depth + 1); }
        catch (Exception e) { obj[p.Name] = $"[unreadable: {e.InnerException?.GetType().Name ?? e.GetType().Name}]"; }
    }
    return obj;
}

static void WriteJson(string path, object? plain)
{
    Directory.CreateDirectory(Path.GetDirectoryName(path)!);
    File.WriteAllText(path, JsonSerializer.Serialize(plain, new JsonSerializerOptions { WriteIndented = true }) + "\n");
}

switch (mode)
{
    case "check":
        Check("war3map.w3i", p => { using var s = File.OpenRead(p); using var r = new BinaryReader(s); _ = r.ReadMapInfo(); });
        Check("war3map.w3e", p => { using var s = File.OpenRead(p); using var r = new BinaryReader(s); _ = r.ReadMapEnvironment(); });
        return failures == 0 ? 0 : 1;

    case "dump":
    {
        var trigDir = Path.Combine(dir, "_triggers");
        Check("war3map.wtg", p =>
        {
            using var s = File.OpenRead(p);
            using var r = new BinaryReader(s);
            var wtg = r.ReadMapTriggers(); // resolves against community TriggerData.Default
            WriteJson(Path.Combine(trigDir, "war3map.wtg.json"), ToPlain(wtg, 0));
            Console.WriteLine($"DUMP  _triggers/war3map.wtg.json ({wtg.TriggerItems.Count} trigger item(s), format {wtg.FormatVersion}{(wtg.SubVersion is null ? "" : $" sub {wtg.SubVersion}")})");
        });
        Check("war3map.wct", p =>
        {
            using var s = File.OpenRead(p);
            using var r = new BinaryReader(s);
            var wct = r.ReadMapCustomTextTriggers();
            WriteJson(Path.Combine(trigDir, "war3map.wct.json"), ToPlain(wct, 0));
            Console.WriteLine($"DUMP  _triggers/war3map.wct.json ({wct.CustomTextTriggers.Count} custom-text trigger(s), format {wct.FormatVersion})");
        });
        return failures == 0 ? 0 : 1;
    }

    case "make-sample": // synthetic test fixture: OUR artifact, made by War3Net itself
    {
        Directory.CreateDirectory(dir);
        var wtg = new MapTriggers(MapTriggersFormatVersion.v7, null) { GameVersion = 2 };
        wtg.TriggerItems.Add(new TriggerCategoryDefinition(TriggerItemType.Category)
        {
            Id = 1, Name = "Sample Category", ParentId = -1,
        });
        wtg.TriggerItems.Add(new TriggerDefinition(TriggerItemType.Gui)
        {
            Id = 2, Name = "Sample Trigger", ParentId = 1,
            Description = "synthetic wtg generated by War3Net for the toolkit test",
            IsEnabled = true, IsInitiallyOn = true,
        });
        using (var s = File.Create(Path.Combine(dir, "war3map.wtg")))
        using (var w = new BinaryWriter(s)) w.Write(wtg);

        var wct = new MapCustomTextTriggers(MapCustomTextTriggersFormatVersion.v1, null)
        {
            GlobalCustomScriptComment = "sample",
            GlobalCustomScriptCode = new CustomTextTrigger { Code = "// global custom script\n" },
        };
        wct.CustomTextTriggers.Add(new CustomTextTrigger { Code = "call DoNothing()\n" });
        using (var s2 = File.Create(Path.Combine(dir, "war3map.wct")))
        using (var w2 = new BinaryWriter(s2)) w2.Write(wct);
        Console.WriteLine("wrote sample war3map.wtg + war3map.wct");
        return 0;
    }

    default:
        Console.Error.WriteLine("usage: wc3-war3net-check check|dump|make-sample <dir>");
        return 2;
}
EOF

echo "building War3Net checker (first run downloads NuGet packages)..." >&2
dotnet build "$WORK" -v q --nologo >/dev/null
case "$MODE" in
    check)       dotnet run --project "$WORK" --no-build -- check "$(cd "$TARGET" && pwd)" ;;
    dump)        dotnet run --project "$WORK" --no-build -- dump "$(cd "$TARGET" && pwd)" ;;
    make-sample) mkdir -p "$TARGET"; dotnet run --project "$WORK" --no-build -- make-sample "$(cd "$TARGET" && pwd)" ;;
esac
